### ISSUE TITLE
add option to throw error instead of break

### ISSUE THREAD

**Issue by no-stack-dub-sack** [jsbin/loop-protect#18]
In some use cases, it might be handy to have loop-protect throw an error instead of cleanly exiting. If you have a coding app, for example, and you want to warn a user of their infinite loop, this feature might be nice. 

With no loop-protect, the code would hang, and this would be bad, with loop protect on, the loop just breaks, and the user might not even realize their problem. Even on JSbin, it would be great to be notified `Error: Timed out after 100ms due to infinite loop` or something like that (especially for new programmers who might not be as adept at picking up on the problem). 

For my particular use case, I needed this, so came up with some derived regexp/replace solution to replace `break` with `throw new Error(...)`, and it works, but how cool would it be to have an optional arg `message`, which if present would cause loop-protect to throw an error with the string for it's message?

```js
  const timeout = 500
  var msg = `Timed out after ${timeout}ms due to infinite loop`

  Babel.registerPlugin('loopProtection', protect(timeout, msg))
  const transform = source => Babel.transform(source, {
    plugins: ['loopProtection'],
  }).code
```

I'm not quite familiar with how babel transforms and AST works, but if this is something you'd consider, I'd be willing to dig in and give it a try.

**Comment by remy** [comment]
Does it already, just didn't document it.

See this test: https://github.com/jsbin/loop-protect/blob/master/test/loop-protect.test.js#L108

**Comment by no-stack-dub-sack** [comment]
@remy damn, and here I am writing a super convoluted solution which can only be described as a hack. 

So how about a PR to update the docs? This is a super useful feature which would be awesome for people to know about.
