### ISSUE TITLE
bad loop protection when an if statement is involved

### ISSUE THREAD

**Issue by Daniel-Hug** [jsbin/loop-protect#3]
Have a look at this JS Bin: http://jsbin.com/milox/2/edit?js,console,output. It demonstrates the following bug:

Start with this JS (the error shouldn't throw):

``` js
if (false) for (var i = 1; i--;) {
    throw Error;
}
```

Loop-protect will preprocess it into the following, which messes up the JS by sticking a semicolon after the `if` statement, making the `for` loop execute when it shouldn't:

``` js
if (false) ;window.runnerWindow.protect({ line: 1, reset: true }); for (var i = 1; i--;) {;
if (window.runnerWindow.protect({ line: 1 })) break;

    throw Error;
}

//# sourceURL=jsbin.milox.2-154.js
//@ sourceURL=jsbin.milox.2-154.js
```

I'm sure this bug is related: https://github.com/jsbin/jsbin/issues/1075
This is not the first time I happened upon a form of this bug while coding merrily. :) Don't make me lose confidence in loop-protect! I'm not sure how helpful it is for JS Bin.

**Comment by yixizhang** [comment]
Created pull request #8 to fix this issue.
